### ISSUE TITLE
Djangoのユーザー認証について調査

### ISSUE THREAD

**Issue by SHIO777** [DECQuando/Synq#39]
- django-allauthで実装するのが良さそうです。

[【第8回】Djangoで日記アプリを作ろう～認証機能実装編～](https://rightcode.co.jp/blog/become-engineer/django-diary-app-make-approval-function)

[django-allauthでログイン機能(ユーザ認証機能)を実装する](https://qiita.com/jansnap/items/62f0de512bc8771ebd58)

**Comment by KG6201** [comment]
PR #92 でdjango-allauthを用いないユーザー認証は導入しました。
