### ISSUE TITLE
画像の権限管理

### ISSUE THREAD

**Issue by SHIO777** [DECQuando/Synq#59]
- 現状は、だれでもmediaフォルダにある画像を見れてしまう。
- 画像の閲覧について、ログインユーザーのみ閲覧できるように権限管理をする

**Comment by KG6201** [comment]
`get_queryset`によるクエリのオーバライドを用いたユーザーのフィルタは以下が参考になった。
https://docs.djangoproject.com/en/4.2/topics/class-based-views/generic-display/#dynamic-filtering
https://qiita.com/aqmr-kino/items/d536e08a715a9fad5720#%E3%83%A2%E3%83%87%E3%83%AB%E3%82%92%E3%83%95%E3%82%A3%E3%83%AB%E3%82%BF%E7%B5%9E%E3%82%8A%E8%BE%BC%E3%81%BF%E3%81%99%E3%82%8B

**Comment by KG6201** [comment]
`DetailView`における`UserPassesTestMixin`を用いた認証は以下が参考になった。
- https://docs.djangoproject.com/ja/4.1/topics/auth/default/#django.contrib.auth.mixins.UserPassesTestMixin
- https://intellectual-curiosity.tokyo/2018/12/06/django%E3%81%AE%E8%A9%B3%E7%B4%B0%E7%94%BB%E9%9D%A2detailview%E3%81%A7%E8%87%AA%E5%88%86%E4%BB%A5%E5%A4%96%E3%81%AE%E3%83%A6%E3%83%BC%E3%82%B6%E3%83%9A%E3%83%BC%E3%82%B8%E3%81%AB%E3%82%A2%E3%82%AF/
